name: Build and push Docker image

on:
  push:
    branches:
      - main
    paths:
      - '**/Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo s"${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build . -t ghcr.io/${{ github.repository }}/node-typescript:latest ./src/node-typescript

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/node-typescript:latest